package org.main.pojo;
// Generated Feb 18, 2017 2:36:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contactinfo generated by hbm2java
 */
@Entity
@Table(name="contactinfo"
    ,catalog="sms_managerengg"
)
public class Contactinfo  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String branch;
     private String year;
     private String college;
     private String emailId;
     private String contact;
     private Date entrydate;

    public Contactinfo() {
    }

    public Contactinfo(String name, String branch, String year, String college, String emailId, String contact, Date entrydate) {
       this.name = name;
       this.branch = branch;
       this.year = year;
       this.college = college;
       this.emailId = emailId;
       this.contact = contact;
       this.entrydate = entrydate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="branch", length=65535)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }

    
    @Column(name="year", length=65535)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    
    @Column(name="college", length=65535)
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }

    
    @Column(name="email_id", length=65535)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="contact", length=65535)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="entrydate", length=10)
    public Date getEntrydate() {
        return this.entrydate;
    }
    
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }




}


