package org.main.pojo;
// Generated Dec 9, 2016 5:34:44 PM by Hibernate Tools 4.3.1



/**
 * Tbupload generated by hbm2java
 */
public class Tbupload  implements java.io.Serializable {


     private Integer id;
     private byte[] uplaodfile;

    public Tbupload() {
    }

    public Tbupload(byte[] uplaodfile) {
       this.uplaodfile = uplaodfile;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public byte[] getUplaodfile() {
        return this.uplaodfile;
    }
    
    public void setUplaodfile(byte[] uplaodfile) {
        this.uplaodfile = uplaodfile;
    }




}


